app/models.py
__author__ = 'jenking'
from . import db

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    def __repr__(self):
        return '<User %r>' % self.username

app/main/forms.py
__author__ = 'jenking'

from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class NameForm(Form):
    name = StringField('Hi,What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
__author__ = 'jenking'
from flask import Flask,render_template
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config[config_name])
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
__author__ = 'jenking'
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
__author__ = 'jenking'

from datetime import datetime
from flask import render_template, session, redirect, url_for, current_app
from .. import db
from ..models import User
from ..email import send_email
from . import main
from .forms import NameForm

@main.route('/',methods=['GET','POST'])
def index():
    form = NameForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.name.data).first()
        if user is None:
            user = User(username=form.name.data)
            db.session.add(user)
            session['known'] = False
            if current_app.config['FLASKY_ADMIN']:
                send_email(current_app.config['FLASKY_ADMIN'], 'New User','mail/new_user', user=user)
        else:
            session['known'] = True
        session['name'] = form.name.data
        return redirect(url_for('main.index'))
    return render_template('index.html',
                           form=form, name=session.get('name'),
                           known=session.get('known', False))

@main.route('/moment/')
def moment():
    return render_template('moment.html', current_time=datetime.utcnow())

@main.route('/test/')
def test():
    return render_template('test.html',name='Jenking',mylist=["one", "two", "three", "four", "five"])

@main.route('/user/<name>/')
def user(name):
    return render_template('user.html', name=name, user='wong')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <title>
            {% block title %}{% endblock %}
        </title>
        <link rel="icon" href="{{url_for('static',filename='favicon.ico')}}" type="image/x-icon" />
        <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}"/>
            {% block cumstom_css %}{% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}

    {% include 'footer.html' %}

    {% block scripts %}
    {% endblock %}
</body>
</html>

app/templates/data.html
{% extends 'base.html'%}
{% block title %}User{% endblock %}
{% block body %}
    <h2>Hello data!</h2>
{% endblock %}

app/templates/footer.html
<script src="{{url_for('static',filename='js/lib/jquery-2.1.4.min.js')}}"></script>
<script src="{{url_for('static',filename='js/lib/underscore.js')}}"></script>
<script src="{{url_for('static',filename='js/lib/backbone.js')}}"></script>
<script src="{{url_for('static',filename='js/lib/template.js')}}"></script>
<script src="{{url_for('static',filename='js/lib/bootstrap.min.js')}}"></script>

app/templates/index.html
{% extends 'base.html'%}
{% block title %}Index{% endblock %}
{% block body %}

    <div  class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% import "bootstrap/wtf.html" as wtf %}
        <div class="page-header">
            <div>
                <h2>Hello,{% if name%}{{name}}{% else %}Stranger{% endif %}!</h2>
                {% if not known %}
                    <p>Pleased to meet you !</p>
                {% else %}
                    <p>Happy to see you again!</p>
                {% endif %}
            </div>
        </div>
        {{ wtf.quick_form(form) }}
    </div>

{% endblock %}

app/templates/moment.html
{% extends 'base.html'%}
{% block title %}Moment{% endblock %}

{% block body %}
    <h2>Hello World</h2>
    <a href="{{ url_for('main.user',name='wong',_external=True) }}">Link1</a>
    <a href="{{ url_for('main.index', page='2') }}">Link2</a>
    <hr>
    <p>{{ moment(current_time).format('LLL')}}</p>
    <p>{{ moment(current_time).fromNow(refresh=True)}}</p>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang('zh-CN') }}
{% endblock%}

app/templates/test.html
{% extends 'base.html'%}
{% block title %}User{% endblock %}
{% block cumstom_css %}
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
{% endblock %}

{% block body %}
    <h2>Hello {{name}}!</h2>
    <ul>
        {% for num in mylist%}
            <li>{{num}}</li>
        {% endfor %}
    </ul>
{% endblock %}

{% block scripts %}
    <script src="{{url_for('static',filename='js/plugin/backbone.localStorage-min.js')}}"></script>
    <script src="{{url_for('static',filename='js/main.js')}}"></script>
{% endblock%}

app/templates/user.html
{% extends 'base.html'%}
{% block title %}User{% endblock %}
{% block body %}
    <h2>Hello {{name}}!</h2>
    <a href="{{ url_for('main.user',name='wong',_external=True) }}">Link1</a>
    <a href="{{ url_for('main.index', page='2') }}">Link2</a>
{% endblock %}